-dontwarn com.google.crypto.tink.proto.**
-dontwarn com.google.crypto.tink.integration.**
-dontwarn com.google.crypto.tink.util.**
-dontwarn com.google.crypto.tink.subtle.**
-dontwarn com.amazonaws.**